# Generated by Django 4.2.14 on 2024-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenguaCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=255)),
                ('temperature', models.FloatField(max_length=255)),
                ('humidity', models.FloatField(max_length=255)),
                ('precipitation', models.FloatField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], default='O', max_length=2, null=True)),
            ],
        ),
    ]
