# Generated by Django 4.2.14 on 2024-08-23 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dengua_case_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguacase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='denguacase',
            name='age',
            field=models.IntegerField(),
        ),
    ]
