# Generated by Django 4.2.14 on 2024-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengua_case_manage', '0002_denguacase_created_by_alter_denguacase_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguacase',
            name='dengue_spread_status',
            field=models.CharField(choices=[('H', 'HIGH'), ('M', 'MODERATE'), ('L', 'LOW')], default='M', max_length=2, null=True),
        ),
    ]
