# Generated by Django 4.2.14 on 2024-08-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dengua_case_manage', '0003_denguacase_dengue_spread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguacase',
            name='latitude',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='denguacase',
            name='longitude',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
